// <auto-generated />
using FinalProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinalProject.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    partial class DataBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FinalProject.Models.Bot", b =>
                {
                    b.Property<int>("BotID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LevelID");

                    b.Property<string>("Recording");

                    b.Property<int>("time");

                    b.HasKey("BotID");

                    b.ToTable("Bot");
                });

            modelBuilder.Entity("FinalProject.Models.HighScore", b =>
                {
                    b.Property<int>("HighScore_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LevelID");

                    b.Property<int>("UserID");

                    b.Property<string>("recording");

                    b.Property<int>("time");

                    b.HasKey("HighScore_ID");

                    b.ToTable("HighScore");
                });

            modelBuilder.Entity("FinalProject.Models.Level", b =>
                {
                    b.Property<int>("LevelID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BackGroundImage");

                    b.Property<string>("LevelObsticles");

                    b.HasKey("LevelID");

                    b.ToTable("Level");
                });

            modelBuilder.Entity("FinalProject.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cash");

                    b.Property<int>("CurrentLevel");

                    b.Property<string>("Email");

                    b.Property<bool>("Nos");

                    b.Property<int>("NosContainers");

                    b.Property<string>("Role");

                    b.Property<bool>("SkinBlue");

                    b.Property<bool>("SkinChrome");

                    b.Property<bool>("SkinGreen");

                    b.Property<bool>("SkinPurple");

                    b.Property<bool>("SkinRed");

                    b.Property<string>("UserName");

                    b.HasKey("UserID");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
